### ISSUE TITLE
AWSAppSyncClient throws error when client.mutation is called from AWSLambda

### ISSUE THREAD

**Issue by desmond-phonegap** [awslabs/aws-mobile-appsync-sdk-js#267]
When AppSync is muations called usign AWSAppSyncClient from Lambda NodeJS it throws "**Network error: Missing optimisticResponse while offline.**"

This happens most of the time while at times it does succesfully gets mutated. What is the best way to communicate or mutate to AppSync from AWS Lambda.
Below is the detailed error message.

```
{ Error: Network error: Missing optimisticResponse while offline.
at new ApolloError (/var/task/node_modules/aws-appsync/node_modules/apollo-client/bundle.umd.js:124:32)
at Object.error (/var/task/node_modules/aws-appsync/node_modules/apollo-client/bundle.umd.js:1088:32)
at notifySubscription (/var/task/node_modules/zen-observable/lib/Observable.js:130:18)
at onNotify (/var/task/node_modules/zen-observable/lib/Observable.js:161:3)
at SubscriptionObserver.error (/var/task/node_modules/zen-observable/lib/Observable.js:220:7)
at notifySubscription (/var/task/node_modules/zen-observable/lib/Observable.js:130:18)
at flushSubscription (/var/task/node_modules/zen-observable/lib/Observable.js:112:5)
at /var/task/node_modules/zen-observable/lib/Observable.js:156:14
at /var/task/node_modules/zen-observable/lib/Observable.js:67:7
at <anonymous>
graphQLErrors: [],
networkError: Error: Missing optimisticResponse while offline.
at /var/task/node_modules/aws-appsync/lib/link/offline-link.js:80:35
at new Subscription (/var/task/node_modules/zen-observable/lib/Observable.js:179:34)
at Observable.subscribe (/var/task/node_modules/zen-observable/lib/Observable.js:258:14)
at /var/task/node_modules/aws-appsync/lib/client.js:151:55
at <anonymous>,
message: 'Network error: Missing optimisticResponse while offline.',
extraInfo: undefined }
```

```
let client = new AWSAppSyncClient({
        url: settings.url,
        region: settings.region,
        auth: {
            type: type,
            apiKey: settings.apiKey,
        },
        disableOffline: false
    });
client.hydrated().then((client,error) => { 
client.mutate({ 
                mutation: updateMutation, 
                variables: { 
                    ID: vehicle.VehicleID,
                    AMUCS: vehicle.AMUCaseStatus
                        }
              })
   })
```

**Comment by undefobj** [comment]
Can you try following the steps outlined here for running with Lambda: https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-node.html#create-a-client-application

Be sure to set `fetchPolicy: 'network-only'` as below where the query is a mutation:
 
```
client.query({ query: query, fetchPolicy: 'network-only' })   //Uncomment for AWS Lambda
```

**Comment by builtbyproxy** [comment]
Do you actually provide it an optimistic response? What does your query/mutation look like?
