### ISSUE TITLE
Availability to specify SSE config on ComplexObject uploading

### ISSUE THREAD

**Issue by shukob** [awslabs/aws-mobile-appsync-sdk-js#327]
>  Note: If your issue/feature-request/question is regarding the AWS AppSync service, please log it in the 
  [official AWS AppSync forum](https://forums.aws.amazon.com/forum.jspa?forumID=280&start=0)

**Do you want to request a *feature* or report a *bug*?**
*feature* request

**What is the current behavior?**
SSE config on ComplexObjectLink does not exist.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
We can specify it in constructor of AppSyncClient

**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**
1.7.0

**Comment by shukob** [comment]
Re: https://github.com/bodybank-sdk/aws-mobile-appsync-sdk-js/commit/d9613eb7d815d313d8f6ce8b2a7152ddfdd499c7

**Comment by elorzafe** [comment]
Hi @shukob, thanks for your comments. We can discuss this with the team. Can you submit a PR for this. 

Thanks!

**Comment by shukob** [comment]
Hi, @elorzafe, thank you for the response. I made  #340 for this, 
but cannot make local test to work. It seems it is not a problem of the modification but that of a configuration. Are there any configuration which is necessary for test to work?
Thanks in advance.

```
Mac-b8f6b110a75b-5:aws-appsync shunpeik$ yarn jest
yarn run v1.13.0
$ /Users/shunpeik/aws-mobile-appsync-sdk-js/packages/aws-appsync/node_modules/.bin/jest
 FAIL  __tests__/link/offline-link.test.ts

    TypeError: __tests__/link/offline-link.test.ts: Emit skipped

      at getOutput (../../node_modules/ts-jest/dist/compiler.js:160:23)
      at Object.compile (../../node_modules/ts-jest/dist/compiler.js:206:25)
      at TsJestTransformer.process (../../node_modules/ts-jest/dist/ts-jest-transformer.js:101:41)

 FAIL  __tests__/client.ts
  ● Test suite failed to run

    TypeError: __tests__/client.ts: Emit skipped

      at getOutput (../../node_modules/ts-jest/dist/compiler.js:160:23)
      at Object.compile (../../node_modules/ts-jest/dist/compiler.js:206:25)
      at TsJestTransformer.process (../../node_modules/ts-jest/dist/ts-jest-transformer.js:101:41)

 FAIL  __tests__/link/complex-object-link.test.ts
  ● Test suite failed to run

    TypeError: __tests__/link/complex-object-link.test.ts: Emit skipped

      at getOutput (../../node_modules/ts-jest/dist/compiler.js:160:23)
      at Object.compile (../../node_modules/ts-jest/dist/compiler.js:206:25)
      at TsJestTransformer.process (../../node_modules/ts-jest/dist/ts-jest-transformer.js:101:41)

```
