### ISSUE TITLE
without disableOffline:true graphql operations failing with error in readFromStore

### ISSUE THREAD

**Issue by attilah** [awslabs/aws-mobile-appsync-sdk-js#343]
I've an AppSync application which is configured to use Cognito.

When I'm configuring the AppSyncClient without the ```disableOffline: true``` option I am ending up with this error upon executing any query:

```
  graphQLErrors: [],
  networkError:
   Error: Can't find field listKiosks on object undefined.
       at /project/node_modules/aws-appsync/node_modules/apollo-cache-inmemory/src/readFromStore.ts:233:15
       at Array.forEach (<anonymous>)
       at StoreReader.diffQueryAgainstStore (/project/node_modules/aws-appsync/node_modules/apollo-cache-inmemory/src/readFromStore.ts:231:26)
       at StoreReader.readQueryFromStore (/project/node_modules/aws-appsync/node_modules/apollo-cache-inmemory/src/readFromStore.ts:178:17)
       at processOfflineQuery (/project/node_modules/aws-appsync/lib/link/offline-link.js:158:34)
       at /project/node_modules/aws-appsync/lib/link/offline-link.js:114:28
       at new Subscription (/project/node_modules/zen-observable/lib/Observable.js:183:34)
       at Observable.subscribe (/project/node_modules/zen-observable/lib/Observable.js:262:14)
       at /project/node_modules/aws-appsync/lib/client.js:175:67,
```

If was quite hard to figure out that disableOffline is needed to make this work.

I don't know what is the expected behavior:

1. Shall it work with offline capabilities in a node application (not necessarily from Lambda only)?

or

2. We could provide a better error message that under node this functionality is not available and if node environment detected, then bail out with a friendly error message during client initialization?

**Comment by stephankaag** [comment]
I do have the same issue and came down to the same questions that you asked. Anyone here who can respond?

**Comment by attilah** [comment]
@stephankaag perhaps it was not clear, but specifying disableOffline: true works like a charm.

**Comment by stephankaag** [comment]
> @stephankaag perhaps it was not clear, but specifying disableOffline: true works like a charm.

I know but I don't want disable offline functionalities. 
However, I found a few related issues so you can ignore my comments here.

**Comment by stephankaag** [comment]
In my case next.js

**Comment by brandomorrill** [comment]
This feels related to issue [102](https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/102)

**Comment by mikeRChambers610** [comment]
@attilah this is a solution that works like a charm if you do not need offline capabilities...
